### ISSUE TITLE
deep_symbolize_keys raises NoMethodError for Hash

### ISSUE THREAD

**Issue by smndiaye** [ruby-i18n/i18n#461] opened 2019-01-08 14:21 UTC
## What I tried to do

Upgraded from 1.2.0 to 1.5.1

## What I expected to happen

deep_symbolize_keys raises NoMethodError for Hash when parsing rails secrets (running capistrano deploy)

## What actually happened

```
NoMethodError: undefined method `deep_symbolize_keys' for #<Hash:0x00007fd2b49d5c40>
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6.1/lib/rails/secrets.rb:30:in `block in parse'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6.1/lib/rails/secrets.rb:24:in `each'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6.1/lib/rails/secrets.rb:24:in `each_with_object'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6.1/lib/rails/secrets.rb:24:in `parse'
config/deploy.rb:45:in `<top (required)>'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/capistrano-3.11.0/lib/capistrano/setup.rb:27:in `load'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/capistrano-3.11.0/lib/capistrano/setup.rb:27:in `block (3 levels) in <top (required)>'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/capistrano-3.11.0/lib/capistrano/configuration/variables.rb:32:in `untrusted!'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/2.5.0/delegate.rb:83:in `method_missing'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/capistrano-3.11.0/lib/capistrano/setup.rb:26:in `block (2 levels) in <top (required)>'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/capistrano-3.11.0/lib/capistrano/application.rb:14:in `run'
/Users/xxx/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/capistrano-3.11.0/bin/cap:3:in `<top (required)>'
/Users/xxx/.rbenv/versions/2.5.3/bin/cap:23:in `load'
```

## Versions of i18n, rails, and anything else you think is necessary

i18n ---> 1.5.1
rails ---> 5.1.4
capistrano ---> 3.x

might be refining deep_symbolize_keys effect 

----
Bonus points for providing an application or a small code example which reproduces the issue.
I will make a sample rails app if needed
Thanks! :heart:

**Comment by radar** [comment] 2019-01-09 21:52
Thank you.

I have been able to reproduce this issue.

### Gemfile

```ruby
source 'https://rubygems.org'

gem 'railties', '~> 5.1.6.1'
gem 'i18n'
```

### script.rb

```ruby
require 'rails/secrets'
require 'active_support/core_ext/string/filters'
require 'securerandom'

ENV['RAILS_MASTER_KEY'] = SecureRandom.hex(16)

Rails::Secrets.write(<<-end_of_secrets)
        shared:
          key: value
        production:
          yeah_yeah: lets-walk-in-the-cool-evening-light
      end_of_secrets

Rails::Secrets.parse([Rails::Secrets.send(:path)], env: :production)
```

### Command

```
bundle exec ruby script.rb
```

### Error

```
Traceback (most recent call last):
	5: from script.rb:14:in `<main>'
	4: from /usr/local/Cellar/asdf/0.4.1/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.6.1/lib/rails/secrets.rb:24:in `parse'
	3: from /usr/local/Cellar/asdf/0.4.1/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.6.1/lib/rails/secrets.rb:24:in `each_with_object'
	2: from /usr/local/Cellar/asdf/0.4.1/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.6.1/lib/rails/secrets.rb:24:in `each'
	1: from /usr/local/Cellar/asdf/0.4.1/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.6.1/lib/rails/secrets.rb:29:in `block in parse'
/usr/local/Cellar/asdf/0.4.1/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.6.1/lib/rails/secrets.rb:29:in `method': undefined method `deep_symbolize_keys' for class `Hash' (NameError)
```

---

This issue appears to be happening because the `rails/secrets.rb` file uses the `deep_symbolize_keys` method that should come from `active_support/core_ext/hash/keys.rb`, but it does not require this file.

Here's the line from Rails that uses that method:

https://github.com/rails/rails/blob/v5.1.6.1/railties/lib/rails/secrets.rb#L28

I consider this a bug with Rails, because at the top of this file they require other things from AS CoreExt:

https://github.com/rails/rails/blob/v5.1.6.1/railties/lib/rails/secrets.rb#L1-L3

As a personal policy, I no longer file issues or open PRs on the Rails project (due to bad past dealings with You-Know-Who).

If you would like this fixed, I suggest two things:

1. Put this line at the top of your `config/deploy.rb`: `require 'active_support/core_ext/hash/keys'`. This will immediately make the issue go away.
2. Open a PR to Rails to add this require line to the top of `secrets.rb`, and while you're there also add a require for `active_support/core_ext/string/filters` too.

It's my belief that `rails/secrets.rb` should be able to be _directly_ required and then used, without having to require additional files as well. It's just bad Ruby code otherwise.

**Comment by smndiaye** [comment] 2019-01-10 13:34
Thank you for your time ! 🙇‍♂️

I will take a deeper look on it then probably will forward the issue to Rails project.

**Comment by smndiaye** [comment] 2019-01-13 09:50
@oniofchaos Sure, it occurs with `1.3.0`, `1.4.0` and `1.5.1`

**Comment by smndiaye** [comment] 2019-01-14 07:43
`Rails::Secrets.parse` is not recommended to be used (cf: rails issue). 
So I am going with another way of parsing secrets file. 
Thanks

**Comment by oniofchaos** [comment] 2019-02-06 18:58
Based on that, seems like it makes sense to close this too and then re-open if you find the issue still occurs with the public API equivalent? @smndiaye 

P.S. Thanks for making the Rails issue and finding out it's a private API!

**Comment by radar** [comment] 2019-02-18 22:01
Closing as I don't think there's anything here I can do.

**Closed** 2019-02-18 22:01 UTC

**Comment by GeminPatel** [comment] 2019-04-04 13:14
I am facing this same issue but for a very simple line in Capfile : YAML.load_file('./config/infra.yml').deep_symbolize_keys

It says: NoMethodError: undefined method `deep_symbolize_keys' for #<Hash:0x00000001f1b0c0>

for ruby 2.4.1 and rails 5.1.7

It works in rails console though.

**Comment by radar** [comment] 2019-04-04 21:42
@geminPatel: this is because you haven’t loaded the activesupport file which includes deep_symbolize_keys. It is not an i18n issue.
