### ISSUE TITLE
[BUG] simple_form + i18n 1.7.1+ causes undefinied downcase for hash exception

### ISSUE THREAD

**Issue by deepj** [ruby-i18n/i18n#515] opened 2020-01-23 00:52 UTC
## What I tried to do

In my current application is used `simple_form` `5.0.1` and `i18n` and the following calling `simple_form` helper - `button`.

## What I expected to happen

No exception

## What actually happened

```
undefined method `downcase' for #<Hash:0x00007f97872634c0>
```

## Versions of i18n, rails, and anything else you think is necessary

- ruby 2.6.5
- rails 6.0.2.1
- simple_form 5.0.1
- i18n (any versions of 1.7.1, 1.8.0, 1.8.1 or 1.8.2)

This snipper causes it

```code
simple_fom_for @object do |form|
  form.button :submit
end
```

I have to downgrade to `1.7.0`, the version which works.

**Comment by radar** [comment] 2020-01-24 21:14
Thank you for the great steps to reproduce this issue. Unfortunately, I am unable to reproduce the issue. 

Could you please try again, and create a repository that reproduces this issue?

Thanks!

**Comment by wulffeld** [comment] 2020-02-07 11:12
This is a duplicate of #514. I just hit the exact same problem and it's to do with nested keys as described in #514.

**Comment by deepj** [comment] 2020-05-07 07:10
@radar I can confirm, adding `rails-i18n` mentioned by you here https://github.com/ruby-i18n/i18n/issues/514#issuecomment-577418929, solves this problem. Anyway, there is a plan to remove `simple_form`, so I guess this can be closed, whatever. Sorry for being late to answer.

**Closed** 2020-05-07 07:19 UTC
Labels: has-repro-steps, waiting
